#pragma once
#include <string>
static const std::string coverPathBack[] = {
	"./Resources/Images/back.png",
	"./Resources/Images/silicon/Silicon-Black-Back.png",
	"./Resources/Images/silicon/Silicon-Cocoa-Back.png",
	"./Resources/Images/silicon/Silicon-Midnight-Blue-Back.png",
	"./Resources/Images/silicon/Silicon-Ocean-Blue-Back.png",
	"./Resources/Images/silicon/Silicon-Pink-Back.png",
	"./Resources/Images/silicon/Silicon-Red-Back.png",
	"./Resources/Images/silicon/Silicon-Sea-Blue-Back.png",
	"./Resources/Images/silicon/Silicon-Stone-Back.png",
	"./Resources/Images/silicon/Silicon-White-Back.png",
	"./Resources/Images/leather/leather-black-back.png",
	"./Resources/Images/leather/leather-midnight-blue-back.png",
	"./Resources/Images/leather/leather-red-back.png",
	"./Resources/Images/leather/leather-saddle-brown-back.png",
	"./Resources/Images/leather/leather-sea-blue-back.png",
	"./Resources/Images/leather/leather-storm-grey-back.png",
	"./Resources/Images/leather/leather-tan-back.png",
};

static const std::string coverPathBackSmall[] = {
	"./Resources/Images/back_small.png",
	"./Resources/Images/silicon/Silicon-Black-Back-small.png",
	"./Resources/Images/silicon/Silicon-Cocoa-Back-small.png",
	"./Resources/Images/silicon/Silicon-Midnight-Blue-Back-small.png",
	"./Resources/Images/silicon/Silicon-Ocean-Blue-Back-small.png",
	"./Resources/Images/silicon/Silicon-Pink-Back-small.png",
	"./Resources/Images/silicon/Silicon-Red-Back-small.png",
	"./Resources/Images/silicon/Silicon-Sea-Blue-Back-small.png",
	"./Resources/Images/silicon/Silicon-Stone-Back-small.png",
	"./Resources/Images/silicon/Silicon-White-Back-small.png",
	"./Resources/Images/leather/leather-black-back-small.png",
	"./Resources/Images/leather/leather-midnight-blue-back-small.png",
	"./Resources/Images/leather/leather-red-back-small.png",
	"./Resources/Images/leather/leather-saddle-brown-back-small.png",
	"./Resources/Images/leather/leather-sea-blue-back-small.png",
	"./Resources/Images/leather/leather-storm-grey-back-small.png",
	"./Resources/Images/leather/leather-tan-back-small.png",
};

static const std::string coverPathFront[] = {
	"./Resources/Images/front.png",
	"./Resources/Images/silicon/Silicon-Black-Front.png",
	"./Resources/Images/silicon/Silicon-Cocoa-Front.png",
	"./Resources/Images/silicon/Silicon-Midnight-Blue-Front.png",
	"./Resources/Images/silicon/Silicon-Ocean-Blue-Front.png",
	"./Resources/Images/silicon/Silicon-Pink-Front.png",
	"./Resources/Images/silicon/Silicon-Red-Front.png",
	"./Resources/Images/silicon/Silicon-Sea-Blue-Front.png",
	"./Resources/Images/silicon/Silicon-Stone-Front.png",
	"./Resources/Images/silicon/Silicon-White-Front.png",
	"./Resources/Images/leather/leather-black-front.png",
	"./Resources/Images/leather/leather-midnight-blue-front.png",
	"./Resources/Images/leather/leather-red-front.png",
	"./Resources/Images/leather/leather-saddle-brown-front.png",
	"./Resources/Images/leather/leather-sea-blue-front.png",
	"./Resources/Images/leather/leather-storm-grey-front.png",
	"./Resources/Images/leather/leather-tan-front.png",
};

static const std::string coverName[] =
{
	"Without Cover",
	"Silicon Black",
	"Silicon Cocoa",
	"Silicon Midnight Blue",
	"Silicon Ocean Blue",
	"Silicon Pink",
	"Silicon Red",
	"Silicon Sea Blue",
	"Silicon Stone",
	"Silicon White",
	"Leather Black",
	"Leather Midnight Blue",
	"Leather Red",
	"Leather Saddle Brown",
	"Leather Sea Blue",
	"Leather Storm Grey",
	"Leather Tan",
};

static const std::string weightTextPath[] = { 
	"./Resources/Images/weight_without_cover.png", 
	"./Resources/Images/weight_silicon_cover.png",
	"./Resources/Images/weight_silicon_cover.png", 
	"./Resources/Images/weight_silicon_cover.png", 
	"./Resources/Images/weight_silicon_cover.png", 
	"./Resources/Images/weight_silicon_cover.png", 
	"./Resources/Images/weight_silicon_cover.png", 
	"./Resources/Images/weight_silicon_cover.png", 
	"./Resources/Images/weight_silicon_cover.png", 
	"./Resources/Images/weight_silicon_cover.png", 
	"./Resources/Images/weight_leather_cover.png",
	"./Resources/Images/weight_leather_cover.png", 
	"./Resources/Images/weight_leather_cover.png", 
	"./Resources/Images/weight_leather_cover.png", 
	"./Resources/Images/weight_leather_cover.png", 
	"./Resources/Images/weight_leather_cover.png", 
	"./Resources/Images/weight_leather_cover.png", 
};